name: white_black
description: White or black app helps you to decide what to wear today based on today's weather.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  geolocator: ^5.3.0
  stats: ^1.0.0
  shared_preferences: ^0.5.7
  flutter_local_notifications: ^1.4.3
  flutter_tts: ^1.2.0
  path_provider: ^1.6.14
  google_maps_flutter: ^0.5.25+3
  http: ^0.12.0+4
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.0.0
  url_launcher: ^5.2.5
  gradient_text: ^1.0.2
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.4+1
  firebase_core: ^0.5.0
  firebase_admob: ^0.9.0
  lottie: ^0.5.1
  provider: ^4.3.2+1
  facebook_audience_network: ^0.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - assets/images/
  - assets/animations/

